// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package database

import (
	"context"
	"time"
)

const createFile = `-- name: CreateFile :one
INSERT INTO files (id, path, created_at, updated_at)
VALUES (?, ?, ?, ?)
RETURNING id, path, created_at, updated_at
`

type CreateFileParams struct {
	ID        int64
	Path      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, createFile,
		arg.ID,
		arg.Path,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files WHERE id = ?
`

func (q *Queries) DeleteFile(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFile, id)
	return err
}

const deleteFilesByUser = `-- name: DeleteFilesByUser :exec
DELETE FROM files
WHERE id IN (
    SELECT file_id FROM files_users WHERE user_id = ?
)
`

func (q *Queries) DeleteFilesByUser(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteFilesByUser, userID)
	return err
}

const getFileByID = `-- name: GetFileByID :one
SELECT id, path, created_at, updated_at FROM files WHERE id = ?
`

func (q *Queries) GetFileByID(ctx context.Context, id int64) (File, error) {
	row := q.db.QueryRowContext(ctx, getFileByID, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFiles = `-- name: ListFiles :many
SELECT id, path, created_at, updated_at FROM files ORDER BY created_at DESC
`

func (q *Queries) ListFiles(ctx context.Context) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, listFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesByUser = `-- name: ListFilesByUser :many
SELECT f.id, f.path, f.created_at, f.updated_at
FROM files f
JOIN files_users fu ON fu.file_id = f.id
WHERE fu.user_id = ?
ORDER BY f.created_at DESC
`

func (q *Queries) ListFilesByUser(ctx context.Context, userID string) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, listFilesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFile = `-- name: UpdateFile :exec
UPDATE files
SET path = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateFileParams struct {
	Path      string
	UpdatedAt time.Time
	ID        int64
}

func (q *Queries) UpdateFile(ctx context.Context, arg UpdateFileParams) error {
	_, err := q.db.ExecContext(ctx, updateFile, arg.Path, arg.UpdatedAt, arg.ID)
	return err
}

const updateFilePath = `-- name: UpdateFilePath :exec
UPDATE files
SET path = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateFilePathParams struct {
	Path      string
	UpdatedAt time.Time
	ID        int64
}

func (q *Queries) UpdateFilePath(ctx context.Context, arg UpdateFilePathParams) error {
	_, err := q.db.ExecContext(ctx, updateFilePath, arg.Path, arg.UpdatedAt, arg.ID)
	return err
}
