// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files_users.sql

package database

import (
	"context"
)

const countUserFiles = `-- name: CountUserFiles :one
SELECT COUNT(*) FROM files_users WHERE user_id = ?
`

func (q *Queries) CountUserFiles(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserFiles, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getFileUsers = `-- name: GetFileUsers :many
SELECT file_id, user_id
FROM files_users
WHERE file_id = ?
`

func (q *Queries) GetFileUsers(ctx context.Context, fileID int64) ([]FilesUser, error) {
	rows, err := q.db.QueryContext(ctx, getFileUsers, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FilesUser
	for rows.Next() {
		var i FilesUser
		if err := rows.Scan(&i.FileID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserFiles = `-- name: GetUserFiles :many
SELECT file_id, user_id
FROM files_users
WHERE user_id = ?
`

func (q *Queries) GetUserFiles(ctx context.Context, userID string) ([]FilesUser, error) {
	rows, err := q.db.QueryContext(ctx, getUserFiles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FilesUser
	for rows.Next() {
		var i FilesUser
		if err := rows.Scan(&i.FileID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkFileToUser = `-- name: LinkFileToUser :exec
INSERT INTO files_users (file_id, user_id)
VALUES (?, ?)
`

type LinkFileToUserParams struct {
	FileID int64
	UserID string
}

func (q *Queries) LinkFileToUser(ctx context.Context, arg LinkFileToUserParams) error {
	_, err := q.db.ExecContext(ctx, linkFileToUser, arg.FileID, arg.UserID)
	return err
}

const unlinkAllFileUsers = `-- name: UnlinkAllFileUsers :exec
DELETE FROM files_users
WHERE file_id = ?
`

func (q *Queries) UnlinkAllFileUsers(ctx context.Context, fileID int64) error {
	_, err := q.db.ExecContext(ctx, unlinkAllFileUsers, fileID)
	return err
}

const unlinkAllUserFiles = `-- name: UnlinkAllUserFiles :exec
DELETE FROM files_users
WHERE user_id = ?
`

func (q *Queries) UnlinkAllUserFiles(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, unlinkAllUserFiles, userID)
	return err
}

const unlinkFileFromUser = `-- name: UnlinkFileFromUser :exec
DELETE FROM files_users
WHERE file_id = ? AND user_id = ?
`

type UnlinkFileFromUserParams struct {
	FileID int64
	UserID string
}

func (q *Queries) UnlinkFileFromUser(ctx context.Context, arg UnlinkFileFromUserParams) error {
	_, err := q.db.ExecContext(ctx, unlinkFileFromUser, arg.FileID, arg.UserID)
	return err
}
