// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"
)

type File struct {
	ID        int64
	Path      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type FilesUser struct {
	FileID int64
	UserID string
}

type User struct {
	ID             string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	SubscriptionID sql.NullString
}
