// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"
)

type File struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type FilesUser struct {
	FileID string
	UserID int64
}

type User struct {
	ID             int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
	SubscriptionID sql.NullString
}
